### ISSUE TITLE
The SafetyNet Attestation API is deprecated and has been replaced by the Play Integrity API.

### ISSUE THREAD

**Issue by IvPod** [CodesFirst/safetynet_attestation#5]
Hey!
Is there a plan and timeline for migration?

Discontinuing the SafetyNet Attestation API: https://developer.android.com/training/safetynet/deprecation-timeline

**Comment by pewiher** [comment]
Hello friend how are you, good afternoon, we plan to launch a new version at the beginning of January, in case there is an event, let us know.

**Comment by ivansapr** [comment]
@pewiher Hi! Any news on update?

**Comment by pewiher** [comment]
@ivansapr 
Hello, good afternoon, a beta update has been added, it will be available tomorrow

**Comment by pewiher** [comment]
safetynet_attestation: ^1.0.0

**Comment by pewiher** [comment]
I will close this thread, in case I have any news with the plugin let me know
